aplicaciones/cursos/urls.py
from django.conf.urls import url
from django.urls import path
from django.contrib.auth.decorators import login_required
from .views import *

# from django.views.static.
urlpatterns = [
    path('', listaCursos.as_view() , name='p_inicio'), 
    path('detalle/<slug:slug_text>/', login_required( detalleCurso.as_view()), name='detalle')   
]

app_name="app_cursos"
  

carrito_compra/urls.py
# from django.conf.urls import url, include

from django.urls import path,include
from django.contrib import admin
from django.views.generic import TemplateView
from aplicaciones.usuarios.views import LogOut, userlogin
from aplicaciones.cursos.views import Index_principal
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', Index_principal.as_view(), name='p_index_principal'),
    path('iniciar/', userlogin, name="iniciar_sesion"),
    path('salir/', LogOut, name='cerrar_sesion'),
    path('carrito/', include('aplicaciones.carrito.urls', namespace='app_carrito')),
    path('cursos/', include('aplicaciones.cursos.urls', namespace='app_cursos')),
    path('usuarios/', include('aplicaciones.usuarios.urls', namespace='app_usuarios')),
]


if settings.DEBUG:
    from django.conf.urls.static import static
    from django.contrib.staticfiles.views import serve as static_serve
    staticpatterns = static(settings.STATIC_URL, view=static_serve)
    mediapatterns = static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns = staticpatterns + mediapatterns + urlpatterns
 

aplicaciones/cursos/models.py
from django.db import models
from django.template.defaultfilters import slugify
from aplicaciones.usuarios.models import Usuario
# Create your models here.
class Categoria(models.Model):

    titulo = models.CharField(max_length=150)
    slug = models.SlugField(editable=False)

    def save(self, *args, **kwargs):
        if not self.id:
            self.slug = slugify(self.titulo)
        super(Categoria, self).save(*args, **kwargs)

    def __str__(self):
        return self.titulo


class Curso(models.Model):
    """docstring for Curso"""
    nombre = models.CharField(max_length=250)
    slug = models.SlugField(editable=False, max_length=150, unique=True)
    resumen = models.TextField(max_length=250, null=True)
    sobre_curso = models.TextField(max_length=2000)
    autores = models.ManyToManyField(Usuario,blank=True)
    portada = models.ImageField(
        upload_to='baners_cursos', null=True)
    duracion = models.IntegerField()
    fecha_creacion = models.DateTimeField(auto_now=True)
    categorias = models.ManyToManyField(Categoria)
    estado = models.BooleanField(default=True)
    es_gratis = models.BooleanField(default=False)
    costo = models.DecimalField(max_digits=5, decimal_places=2, default=0.00)
    descuento = models.DecimalField(
        max_digits=5, decimal_places=2, default=0.00)

    def __str__(self):
        return self.nombre

    def save(self, *args, **kwargs):
        if not self.id:
            self.slug = slugify(self.nombre)
        super(Curso, self).save(*args, **kwargs)
    

aplicaciones/cursos/views.py
from django.shortcuts import render
from django.views.generic import View,TemplateView,DetailView,ListView
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import Curso as mis_cursos
# Create your views here.

class Curso(TemplateView):
    template_name = 'cursos/cursos.html'

class Index_principal(TemplateView):
    template_name = 'index.html'

    def get_context_data(self, **kwargs):
        context = super(Index_principal,
                        self).get_context_data(**kwargs)
        context['cursos'] = mis_cursos.objects.filter(estado=True)
        return context


class listaCursos(View):

    template_name = 'cursos/cursos.html'

    def get_context_data(self, **kwargs):
        context = super(listaCursos,
                        self).get_context_data(**kwargs)
        context['cursos'] = mis_cursos.objects.filter(estado=True)
        return context


#Vistas basadas en Clases

class listaCursos(ListView):
    model = mis_cursos
    template_name = "cursos/cursos.html"
    context_object_name="lista_cursos"


class detalleCurso(DetailView):
    model = mis_cursos
    template_name="cursos/curso_detalle.html"

    def get_queryset(self,slug_text,**kwargs):        
    	return mis_cursos.objects.get(slug = slug_text, estado = True)

    def get_context_data(self,slug_text,**kwargs):
	    context = {}
	    context['curso_detalle'] = self.get_queryset(slug_text)
	    return context

    def get(self,request,slug_text,*args,**kwargs):
	    return render(request,self.template_name,self.get_context_data(slug_text))
    


#Vistas basadas en funciones
@login_required
def lista_cursos(request):
    lista_cursos =  mis_cursos.objects.all()
    context = {'lista_cursos':lista_cursos}
    return render(request,'cursos/cursos.html', context)

@login_required
def detalle_curso(request, slug_text):
    curso_detalle = mis_cursos.objects.get(slug = slug_text)
    print(curso_detalle)
    context = {'curso_detalle':curso_detalle}
    return render(request, 'cursos/curso_detalle.html', context)

aplicaciones/cursos/templates/cursos/curso_detalle.html
{% extends "base.html" %} {% load %} {% block contenido %}
<div class="container" style="max-width: 1240px !important;">
    <div class="row pt-5">
        <div class="col-md-8">
            <div class="card p-5">
                <div class="card-head">
                    <h1><strong>{{ curso_detalle.nombre}}</strong></h1>
                </div>
                <div class="card-body">

                    <br/>
                    <p class="font-light f-400">{{ curso_detalle.sobre_curso }}</p>
                    <!-- <h5 class="c-text">Descripcion:</h5>
                    <p class="font-light f-400">{{curso_detalle.resumen}}</p> -->
                    <a href="#" target="_blank" rel="noopener noreferrer">


                    </a>
                    <p><span class="c-text" style="font-weight:500">Autores:</span>{% for autor in curso_detalle.autores.all %} <span class="font-light">{{ autor }},</span>{% endfor %}</p>
                    <p><span class="c-text" style="font-weight:500">Duracion:</span> <span class="font-light">{{ curso_detalle.duracion }} horas</span></p>

                    <p><span class="c-text" style="font-weight:500">Categoria:</span>{% for cat in curso_detalle.categorias.all %}
                        <span class="font-light">{{cat}},</span> {% endfor %}</p>
                    <span style="font-size: 0.8rem; font-weight:400; color: #0d6ca9f7;">Actualizado: {{ curso_detalle.fecha_creacion|date:"M, Y" }}</span>
                </div>
            </div>
        </div>
        <div class="col-md-4 pt-4 text-center">
            <img src="{{curso_detalle.portada.url}}" alt="" width="400px">
            <hr/>
            <div class="row text-center">
                <div class="row" style="width: 100%;">{% if curso_detalle.es_gratis %}
                    <button class="btn btn-danger" style="width: 100%;">Gratis</button> {% else %}
                    <button class="btn btn-info" style="width: 100%;">S/. {{curso_detalle.costo}}</button> {% endif %}

                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

aplicaciones/cursos/templates/cursos/cursos.html
{% extends "base.html" %} {% block contenido %}

<div class="container">
    <h2>Nuestros Cursos</h2>
</div>

<div class="container">
    <br>
    <div class="row justify-content-center row-cur">
        {% for curso in lista_cursos %}
        <div class="col-md-4 col1">
            <div class="card box-shadow m-3" style="font-size:0.9rem;">

                <div class="card-head">
                    <a href="{% url 'app_cursos:detalle' curso.slug %} ">
                        <img src=" {{curso.portada.url}} " class="img-fluid " alt=" " width="300px " height="300px ">
                    </a>

                    <a href="# ">
                        <div class="mask "></div>
                    </a>
                </div>

                <!--content-->
                <div class="card-body p-4 ">
                    <!--Title-->
                    <a href="# ">
                        <h4 class="card-title " style="font-size:1.3rem ">{{curso.nombre}}</h4>
                    </a>
                    <hr>
                    <!--Text-->
                    <p class="card-text ">{{ curso.resumen}}</p>

                </div>
                <!--content-->
                <!-- footer -->
                <div class="card-data">
                    <ul>
                        {% if curso.es_gratis %}
                        <button class="btn" style="background-color:#d10404c9; color: white;">Gratis</button> {% else %}
                        <button class="btn" style="background-color: #8b034ed9; color:white;">S/. {{curso.costo}}</button> {% endif %}
                    </ul>
                </div>
                <div class="container p-3">
                    <a href="{% url 'app_cursos:detalle' curso.slug %} "> <button class="btn btn-primary " style="cursor:pointer ">INSCRIBIRME AHORA</button> <a/>
                </div>

                <!-- footer -->
            </div>
        </div>
        {% endfor %}
    </div>
</div>

{% endblock %}